### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by abdulazizm** [Xilinx/pyxir#31]
Working with ZCU104 Edge device. Using apache TVM workflow with VItis AI on top of PYNQ image. Tensorflow fopor aarch64 doesnt comes with pynq? do i need to compile and use my own tensorflow? or did I miss anything?

```
root@pynq:~/tvm/python# python3 -c 'import pyxir'
/usr/local/lib/python3.6/dist-packages/pyxir-0.1.6-py3.6-linux-aarch64.egg/pyxir/runtime/__init__.py:34: UserWarning: Could not load `cpu-tf` runtime because of error: No module named 'tensorflow'
  .format(e))

```

**Comment by jtuyls** [comment]
@abdulazizm You don't need Tensorflow on the Pynq board to do inference. Tensorflow is only needed for doing quantization and compilation on the host machine, that's why you see the warning. I think it's unclear however, so we will remove the warning.

**Comment by abdulazizm** [comment]
@jtuyls Sure thats helpful. I remember while reading docs in tvm saying that they do on-the-fly quantization - but not sure this applies for EDGE devices too

**Comment by jtuyls** [comment]
@abdulazizm We can only quantize and compile on the host machine. If you target edge devices, you use the on-the-fly quantization flow on the host to quantize and cross-compile. You can find a full example here: https://github.com/Xilinx/pyxir/tree/master/examples/tvm
