### ISSUE TITLE
RuntimeModule's load function member produces segmentation fault

### ISSUE THREAD

**Issue by settle** [Xilinx/pyxir#35]
@jornt-xilinx

I've successfully exported and then imported the Runtime Module on an x86_64 host targeting an DPUCADX8G using the following code to import the exported runtime module:

        std::ifstream in_file(rt_mod_holder_filename);
        std::stringstream buffer;
        buffer << in_file.rdbuf();
        std::string serialized_rt_mod = buffer.str();
        in_file.close();

        std::istringstream sstream(serialized_rt_mod);
        rt_mod_holder.reset(new pyxir::runtime::RuntimeModule());
        rt_mod_holder->deserialize(sstream);

However, if I replace the above with the load function in the RuntimeModule class, i.e.,

        rt_mod_holder->load(rt_mod_holder_filename);

I get the following segmentation fault error:

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffb84f2d91 in pyxir::ISerializable::deserialize (this=0x0, sstream=...) at ./pyxir/include/pyxir/runtime/../common/serializable.hpp:41

As far as I know, the two should produce equivalent results, or else something is wrong with the load function.  One thing I noticed when diving into the [load function](https://github.com/Xilinx/pyxir/blob/5cbf761770af5cd438a3359b77a5165b04788b48/include/pyxir/runtime/runtime_module.hpp#L128) is that I don't see a similar reset function call as the verbose code version above.

**Comment by jtuyls** [comment]
@settle I guess the `rt_mod_holder` is a `nullptr` in this case and therefore the reset is needed for initialization. I changed the load to a static function to avoid this issue of potentially not having initialized the RuntimeModule: https://github.com/Xilinx/pyxir/pull/37. Could you have a look?

**Comment by jornt-xilinx** [comment]
Closed this issue as this was fixed with https://github.com/Xilinx/pyxir/pull/37
