### ISSUE TITLE
Ultra96 v2: [DNNDK] DPU configuration mismatch

### ISSUE THREAD

**Issue by Bonjuor-zyx** [Xilinx/pyxir#39]
Hi, I tried the pyxir/examples/tvm/, and I almost succeeded. But when I ran the program on the ultra96 board, I got the error.
![image](https://user-images.githubusercontent.com/54531686/116815859-1755b580-ab92-11eb-8421-950b64aa3398.png)

I checked the dpu version on the host and the board, I found they were both v1.4.1.
host
![image](https://user-images.githubusercontent.com/54531686/116815918-67cd1300-ab92-11eb-8e0a-73e460c30701.png)
board
![image](https://user-images.githubusercontent.com/54531686/116815938-84694b00-ab92-11eb-8a21-2f4cbf880062.png)
I think my situation is really like this [issue ](https://forums.xilinx.com/t5/AI-and-Vitis-AI/DNNDK-DPU-configuration-mismatch-for-kernel-xp0-on-ultra96v2/m-p/1200511), but I don't know how to fix it. I know using the vai_c_ to compile the model needs an 'arch.json', I guess lacking the file for ultra96 may cause the isssue, but I don't know how pyxir uses it.

By the way, I didn't use the PYNQ2.6-Z2 image for ultra96v2, which the tvm doc says, I used PYNQ2.6-Ultra96V2, I think they were different boards, and I didn't boot successfully using the PYNQ2.6-Z2 image when I try.
![image](https://user-images.githubusercontent.com/54531686/116816481-ab288100-ab94-11eb-88a6-8b3759bd5b6c.png)
![image](https://user-images.githubusercontent.com/54531686/116816419-6997d600-ab94-11eb-9214-e4ec0775e151.png)

I would appreciate it very much, if you can help me solve the problem.

**Comment by jtuyls** [comment]
Hi @Bonjuor-zyx, yes, this looks like a mismatch between the DPU IP version the model was compiled for and the DPU IP version on the board. Which version of pynq-dpu are you using (`python3 -c "import pynq_dpu; print(pynq_dpu.__version__)"`)? 

> By the way, I didn't use the PYNQ2.6-Z2 image for ultra96v2, which the tvm doc says, I used PYNQ2.6-Ultra96V2, I think they were different boards, and I didn't boot successfully using the PYNQ2.6-Z2 image when I try.

Ok, this Z1/Z2 comments looks wrong or out-of-date indeed. Thanks for letting us know.

**Comment by Bonjuor-zyx** [comment]
Hi @jtuyls, thanks for your comment! For this try, I used `pynq-dpu 1.2.0` as the[ tvm doc](https://tvm.apache.org/docs/deploy/vitis_ai.html) says,
![image](https://user-images.githubusercontent.com/54531686/117232844-967a1080-ae54-11eb-9811-15e59ac59502.png)

At this moment, I tried another doc,  [Xilinx Vitis-AI/external/tvm](https://github.com/Xilinx/Vitis-AI/tree/master/external/tvm), and I also got an [issue](https://github.com/Xilinx/Vitis-AI/issues/404), so my board now is running `pynq-dpu1.3.0`. 

I think the doc from tvm uses vitis-ai 1.2 and the doc from xilinx uses vitis-ai 1.3, the `lib_dpu.so` is generated as the tvm doc says, and the `tvm_dpu_cpu.so` is from xilinx doc, they are both close to success, just one step. 
![image](https://user-images.githubusercontent.com/54531686/117234475-a810e780-ae57-11eb-9c63-e014d50ca779.png)
The board died after showing the first message.

I believe they are both caused by the version inconsistence problem, I would appreciate it very much, if you can tell me how to set the tvm + vitis-ai flow for the ultra96 v2 board, I think I need a doc for ultra96 v2, thanks a lot!!

**Comment by Bonjuor-zyx** [comment]
@jtuyls , great thanks for your help, I think pynq-dpu v1.3.2 will work on the ultra96 v2 board. Recently, I used the zcu104 board to do the experiment, it works fine, after I finish all the data collection, I'll have a try to do it on the ultra96 v2 board.
