### ISSUE TITLE
Question about onnxruntime execution on edge

### ISSUE THREAD

**Issue by 0b11101010** [Xilinx/pyxir#41]
Hello everyone,

I've seen the commit "Create DPUCZDX8G (zcu104, zcu102, SOM and Ultra96) VART flow"  and wanted to ask that 
Is it possible to use onnxruntime on edge devices with this commit?

**Comment by jtuyls** [comment]
@0b11101010 No, not yet, we will first have to get this PR merged into ONNX Runtime: https://github.com/microsoft/onnxruntime/pull/6690

**Comment by 0b11101010** [comment]
Hello @jtuyls,
Thanks for the reply. I see the PR has been merged. Can you recommend some documents to follow if possible right now to give it a try?

**Comment by jtuyls** [comment]
@0b11101010 Yes, PR has been merged but the documentation still has to be updated to show how to use the added DPU targets. This is WIP, but you can have a look already here: https://github.com/edelaye/onnxruntime/blob/gh-pages-update-vitis-ai-doc-1/docs/reference/execution-providers/Vitis-AI-ExecutionProvider.md
