### ISSUE TITLE
Tensorflow Yolov3 compiles but killed while loading in EDGE device using tvm.runtime.load_module()

### ISSUE THREAD

**Issue by abdulazizm** [Xilinx/pyxir#43]
Used the same script and environment as mentioned by @jornt-xilinx here: https://discuss.tvm.apache.org/t/annotation-error-with-vitis-ai-in-tvm/8690/19?u=abdulazizm

Can able to successfully compile the lib_dpu_arm.so but couldnt load in ZCU104. 
```
root@pynq:/home/xilinx# python3 run_tf_yolo.py
Mounting tvm runtime library
Killed
root@pynq:/home/xilinx# 
```
This is the code I use. Not sure if I missed anything. I could able to load deeplabv3 based on pytorch. Hope there shoulnot be any changes needed wrt Pytorch vs Tensorflow framework in runtime code.
```
############################################################
## Load TVM - DPU runtime module
############################################################
print("Mounting tvm runtime library")
lib_path  = os.path.join("/home/xilinx/yolov3_libs/tvm_dpu_arm.so")
lib = tvm.runtime.load_module(lib_path)
print("TVM runtime mount successful")
mod = graph_executor.GraphModule(lib["default"](tvm.cpu()))
```
Thanks,
Abdul.

**Comment by jtuyls** [comment]
@abdulazizm Could you execute `dmesg | grep -i kill` in the terminal on the device? I think this might be an out-of-memory issue and you might have to add some swap space.

**Comment by abdulazizm** [comment]
@jornt-xilinx Yupp you are exactly correct and I am amazed. That seems to be out of memory issue. I have fixed the issue as you mentioned adding swap memory. Could able to inference at ~130ms.

```
========================================
Inference time: 129.77 ms | 0.13 s
========================================

```
