### ISSUE TITLE
Support for MaxPool autopad attribute SAME_UPPER

### ISSUE THREAD

**Issue by FireFox317** [Xilinx/pyxir#44]
Hey @jornt-xilinx, @jtuyls and everybody else !

I'm trying to use pyxir to convert a yolov4-tiny onnx model to XIR, and eventually run it on a Edge DPU. When trying to convert the model using `from pyxir.frontend.onnx.base import from_onnx` I get the following error:
```python
>>> xmodel = from_onnx(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.2.0-py3.6-linux-x86_64.egg/pyxir/frontend/onnx/base.py", line 48, in from_onnx
    return _from_onnx(onnx_model, postprocessing=postprocessing)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.2.0-py3.6-linux-x86_64.egg/pyxir/frontend/onnx/base.py", line 165, in _from_onnx
    Xs = registry[op_type](wrapped_node, params, xmap)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.2.0-py3.6-linux-x86_64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py", line 116, in __base_onnx_2_xlayer
    Xs = onnx_2_xlayer_func(node, params, xmap)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.2.0-py3.6-linux-x86_64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py", line 527, in max_pool
    .format(auto_pad))
ValueError: MaxPool autopad attribute not supported but was: SAME_UPPER
```

I was wondering whether it is possible to add support for this feature, or to somehow work around the problem?

Thanks in advance!

**Comment by FireFox317** [comment]
I kinda solved this, but i'm not sure if this is actually correct. I copied some code from the Conv layer:
```diff
diff --git a/python/pyxir/frontend/onnx/ops/onnx_l2_convolution.py b/python/pyxir/frontend/onnx/ops/onnx_l2_convolution.py
index 4bea0a8..bea2d73 100644
--- a/python/pyxir/frontend/onnx/ops/onnx_l2_convolution.py
+++ b/python/pyxir/frontend/onnx/ops/onnx_l2_convolution.py
@@ -522,7 +522,7 @@ def max_pool(node: NodeWrapper,
         else [1, 1]
     stride_h, stride_w = strides

-    if auto_pad != 'NOTSET' and auto_pad != 'VALID':
+    if auto_pad != 'NOTSET' and auto_pad != 'VALID' and auto_pad != 'SAME_UPPER':
         raise ValueError("MaxPool autopad attribute not supported but was: {}"
                          .format(auto_pad))
     if storage_order != 0:
@@ -535,6 +535,15 @@ def max_pool(node: NodeWrapper,
     # TODO move internal pool padding to [pad_ht, pad_hb, pad_wl, pad_wr]
     padding = [padding[i] for i in [0, 2, 1, 3]]

+    if auto_pad == 'SAME_UPPER':
+        pad_h = int((in_h - 1) * stride_h - in_h +
+                        (dil_h * (kernel_h - 1) + 1))
+        pad_w = int((in_w - 1) * stride_w - in_w +
+                    (dil_w * (kernel_w - 1) + 1))
+        pad_ht, pad_hb = pad_h // 2, pad_h - (pad_h // 2)
+        pad_wl, pad_wr = pad_w // 2, pad_w - (pad_w // 2)
+        padding = [pad_ht, pad_hb, pad_wl, pad_wr]
+
     # TODO dilations
     if dilations != [1, 1]:
         raise NotImplementedError("Dilations are expected to be [1, 1] for"

```

**Comment by jtuyls** [comment]
@FireFox317 Yes, we will add support for SAME_UPPER/SAME_LOWER auto_pad attributes in pooling layers.

The auto_pad conversion code doesn't look correct to me actually. It should be like this:
```
pad_h = (out_h - 1) * stride_h + (dil_h * (kernel_h - 1) + 1) - in_h
```
with 
```
out_h = ceil(in_h / stride_h)
```
The SAME_UPPER Conv implementation might be wrong then. I will have a look at that one too.

**Comment by FireFox317** [comment]
@jtuyls Thanks for the response!

That's a coincidence, because I also just figured out that the padding code of Conv is indeed incorrect. (Was actually typing up another issue xd)

I'm looking forward to the fix, and if you don't have to time to fix it, I can PR the change.

**Comment by jtuyls** [comment]
@FireFox317 If you want to have a go at it, feel free to do so. Otherwise, I will start working on it later today. Let me know what you prefer.

**Comment by FireFox317** [comment]
@jtuyls I'm not too familiar with the codebase, so I would prefer for you to do it :)

I also ran into another problem, where partitioning a graph would get rid of all the subgraphs and only return the subgraph with the most calculations. However that is not valid for my use case, since I want to quantize and run multiple subgraphs on a Zynq MpSoc. But it might be better to create another issue for that, since it is not relevant to this issue.

**Comment by jtuyls** [comment]
@FireFox317 Sure, I will do it. Regarding the partitioning, that's happening on purpose due to some earlier runtime limitations (for DPUCADX8G). It should be possible for the Zynq DPU flow, but there is some work needed to enable that. Feel free to open an issue for this.

**Comment by jornt-xilinx** [comment]
Closing this issue as the PR https://github.com/Xilinx/pyxir/pull/49 has been merged into dev.
