### ISSUE TITLE
BiasAdd is not an input for Relu

### ISSUE THREAD

**Issue by hossam-snke** [Xilinx/pyxir#70]
https://github.com/Xilinx/pyxir/blob/506e8ac176c04b5d7e75ffe7ecbb1f2c4caa6498/python/pyxir/contrib/target/components/DPUCZDX8G/zcu104_op_support.py#L350

Hi @jornt-xilinx ,
Is it possible to add "BiasAdd" to the check-list of valid inputs for Relu operation. Because I got an issue when I had a sequence as  conv+add+Relu, the Relu operation was annotated as unsupported by DPU because BiasAdd is not one of the check list. This leads to issue in the graph annotation and partitioning

**Comment by jornt-xilinx** [comment]
Hi @hossam-snke, yes, this is a bug introduced in v0.3.1 and has already been fixed in dev: https://github.com/Xilinx/pyxir/commit/6ba0fd8140eead568f5524e5e1c45d67b8370d42. We will also push the fix to rel-v0.3.1.
