### ISSUE TITLE
Instance segmentation

### ISSUE THREAD

**Issue by abdulazizm** [Xilinx/pyxir#84]
have anyone successfully compiled any instance segmentation model for xilinx hardware? tried maskrcnn, yolact compilation using tvm (my hardware - zcu104) but no luck

**Comment by jtuyls** [comment]
Hi @abdulazizm, we have an FPN segmentation model running in regressions. And I have run a MaskR-CNN model before too. We will look at the Yolact model in the other issues. Thanks for reporting!

**Comment by abdulazizm** [comment]
Thanks for the reply @jtuyls . Hope you can help me to clear blockers I have in compilation of maskrcnn and yolact in other issues.
